ALTER TABLE "Workspace"
  ADD COLUMN "planId" TEXT NOT NULL DEFAULT 'free',
  ADD COLUMN "billingStatus" TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN "currentPeriodStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "currentPeriodEventCount" INTEGER NOT NULL DEFAULT 0;
