import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const pixelPath = resolve(root, "packages/pixel/dist/index.global.js");
const outputPath = resolve(root, "apps/worker/src/generated-pixel.ts");

const pixelScript = await readFile(pixelPath, "utf8");
const source = `// Generated by scripts/embed-pixel.mjs. Do not edit by hand.\nexport const pixelScript = ${JSON.stringify(pixelScript)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
